""" A django model generated with django-csvimport csvinspect
    which used OKN messytables to guess data types - may need some manual tweaks!
"""
from django.db import models


class Feira(models.Model):
    ''' Autogenerated model file csvimport Wed Mar 22 20:15:54 2017 '''

    id = models.IntegerField(default=0, null=False, primary_key=True, blank=False)
    long = models.IntegerField(default=0, null=True, blank=True)
    lat = models.IntegerField(default=0, null=True, blank=True)
    setcens = models.IntegerField(default=0, null=True, blank=True)
    areap = models.IntegerField(default=0, null=True, blank=True)
    coddist = models.IntegerField(default=0, null=True, blank=True)
    distrito = models.CharField(null=True, max_length=50,blank=True)
    codsubpref = models.IntegerField(default=0, null=True, blank=True)
    subprefe = models.CharField(null=True, max_length=50, blank=True)
    regiao5 = models.CharField(default='', max_length=6, blank=True)
    regiao8 = models.CharField(default='', max_length=7, blank=True)
    nome_feira = models.CharField(null=True, max_length=50, blank=True)
    registro = models.CharField(default='', max_length=6, blank=True)
    logradouro = models.CharField(null=True, max_length=100, blank=True)
    numero = models.IntegerField(default=0, null=True, blank=True)
    bairro = models.CharField(null=True, max_length=100,blank=True)
    referencia = models.CharField(null=True, max_length=200,blank=True)

    class Meta:
        managed = False
        db_table = u'"feira"'
